"""Wordlist for generated passphrases.

1296 words of 4-6 lowercase letters, from the standard English dictionary, with
these removed:

  * proper nouns -- rejected BEFORE lowercasing, since doing it after lets
    "adam" and "acuff" through;
  * anything offensive, matched by substring so inflections go too. A passphrase
    is written on paper and read aloud to another person; it must never be
    something the user would rather not say;
  * homophone pairs that are ambiguous when spoken ("plain"/"plane");
  * redundant plurals and inflections whose stem is also present.

Six words give ~62 bits. With Argon2id costing 1.3 s per guess, brute force runs
to roughly 10^11 years -- the wordlist is not the weak link here.
"""

WORDS = (
    "aback", "abase", "abbot", "abide", "abjure", "abler", "ably", "abuser", "accuse",
    "aces", "acrid", "across", "acumen", "adieu", "admin", "adopt", "adore", "adorn",
    "adroit", "adult", "advice", "adware", "adze", "aerate", "aerie", "afar", "affix",
    "affray", "after", "again", "ageing", "agenda", "ages", "aghast", "aiding",
    "alined", "alive", "allure", "aloud", "also", "always", "amazed", "amebic", "ameer",
    "amend", "amidst", "ampul", "amuck", "amuse", "anew", "angels", "angina", "angry",
    "anode", "anoint", "antler", "anyway", "aortae", "apart", "aped", "apiary", "aping",
    "append", "aptly", "arcade", "arcane", "area", "aright", "arise", "arms", "artier",
    "artist", "arty", "asked", "asking", "asleep", "astral", "atomic", "attain",
    "attend", "attics", "audio", "auks", "avatar", "awaken", "azure", "backup", "baize",
    "balled", "balm", "banana", "bandy", "bang", "barium", "barred", "basal", "baser",
    "bast", "batch", "bath", "bawl", "beater", "beeves", "befall", "befell", "before",
    "beheld", "belay", "belie", "belied", "belong", "bends", "beset", "beside", "biked",
    "bikini", "billow", "binge", "binged", "biped", "blah", "blare", "blat", "blazed",
    "bldg", "bleed", "blench", "bling", "blintz", "blithe", "bobbed", "bobbin",
    "bodice", "bogey", "bogie", "bolero", "bonbon", "bonnet", "booing", "bootie",
    "bops", "border", "boron", "boss", "bottom", "bowed", "bravo", "brew", "bribed",
    "bronco", "broth", "bruin", "budded", "bugged", "bugled", "bugler", "bulged",
    "bulk", "bums", "burnt", "burred", "bushel", "buss", "buying", "buzz", "buzzes",
    "byte", "byway", "cabby", "cachet", "caddy", "cadged", "cages", "cairn", "calif",
    "caliph", "call", "canard", "canoe", "canyon", "carbs", "card", "carpal", "carpel",
    "cars", "cased", "catted", "caucus", "cavil", "cells", "champ", "chaser", "cheeky",
    "cheery", "chew", "chide", "chiles", "chilli", "chimed", "chino", "chisel", "chit",
    "choosy", "choppy", "chose", "chum", "chunky", "circa", "circle", "cirrus", "cited",
    "clamp", "clasp", "clime", "clinic", "clop", "clunk", "clutch", "clxii", "coax",
    "cobweb", "code", "coded", "coerce", "coital", "colic", "comely", "comfy", "coming",
    "concur", "condo", "conga", "convex", "cooing", "cookie", "coop", "cork", "corny",
    "corral", "cosmic", "costly", "coupe", "course", "coyer", "crafts", "cramp",
    "crank", "crew", "croak", "crouch", "cruet", "crufty", "crumb", "cubs", "cuckoo",
    "cudgel", "cums", "curd", "curl", "curs", "curtsy", "curve", "cuss", "cuter",
    "cystic", "dadoes", "daft", "daily", "dainty", "damson", "dash", "data", "dated",
    "davit", "dding", "deaf", "deafen", "deal", "debase", "debate", "decal", "decent",
    "deject", "dells", "derive", "dermis", "detour", "device", "devoid", "dewier",
    "dewlap", "digger", "dike", "dims", "dipped", "dire", "direst", "dirt", "dishes",
    "dismal", "disuse", "diva", "dived", "divine", "divot", "djinni", "docile",
    "dollop", "dome", "donor", "down", "doze", "dozed", "dragon", "draw", "drawl",
    "dress", "dries", "droopy", "dryad", "drys", "dunned", "duties", "easing", "echo",
    "either", "elated", "elbow", "elided", "ells", "elude", "embed", "embody", "emceed",
    "emend", "emit", "emoted", "enact", "engine", "enlist", "entail", "epic", "epoxy",
    "ergo", "erotic", "espied", "espies", "esters", "etch", "ethic", "eureka", "even",
    "evolve", "excise", "exempt", "exert", "exotic", "fabric", "facade", "facet",
    "faded", "fakir", "fallen", "fans", "fast", "fathom", "fault", "faun", "fawn",
    "feast", "fees", "femora", "fence", "ferric", "fest", "fibber", "fiddly", "fiend",
    "fiery", "filch", "fill", "filth", "fired", "fishes", "fitted", "fixing", "fizzy",
    "flag", "flagon", "flail", "flash", "flax", "flies", "fliest", "flip", "flock",
    "floozy", "florae", "fluky", "flunky", "flux", "fobbed", "foggy", "food", "fool",
    "forage", "forced", "forego", "fossil", "foxier", "foxing", "foyer", "frack",
    "freak", "freaky", "free", "fresco", "fridge", "froth", "ftping", "ftps", "fudge",
    "fugue", "full", "futile", "fuzed", "gaiety", "galled", "gamier", "gamin", "gamut",
    "gannet", "gape", "gaps", "garden", "gargle", "garnet", "garter", "gate", "gayest",
    "gazed", "geld", "gems", "genie", "genii", "geode", "germ", "gerund", "geyser",
    "gibe", "gibed", "gigged", "gilt", "ginkgo", "gins", "gird", "girth", "gladly",
    "glaze", "glee", "glide", "glitzy", "glob", "glop", "gloved", "glue", "gluten",
    "goblin", "gobs", "gods", "goober", "gotcha", "gouge", "grad", "grade", "graft",
    "grasp", "greet", "grocer", "groove", "ground", "grove", "growl", "grue", "guest",
    "gull", "gully", "guppy", "gurgle", "gusto", "gusty", "guying", "gybe", "gybing",
    "haggle", "haiku", "haloes", "harm", "harrow", "having", "heals", "hearth", "heft",
    "heifer", "held", "helium", "helm", "helmet", "hence", "hepper", "hereto", "hermit",
    "hero", "hewn", "hike", "hiker", "hilt", "hipper", "hitter", "hoard", "hobo",
    "holier", "homers", "homey", "homing", "honey", "honk", "hoods", "hookah", "hopped",
    "horns", "horror", "hours", "houses", "hubris", "huffy", "hugely", "hugs", "human",
    "hunk", "hurtle", "hustle", "hyphen", "hyping", "ideal", "idling", "idly", "ignite",
    "iguana", "impugn", "incing", "incubi", "infant", "infuse", "injure", "inkier",
    "inland", "inside", "into", "intone", "intuit", "iodine", "iodize", "irate",
    "irony", "jading", "jaunt", "jawed", "jets", "jibs", "jiffy", "jigger", "jihad",
    "jinn", "jive", "jiving", "jobber", "jocose", "jogs", "jolt", "joshes", "joys",
    "judged", "junky", "just", "kale", "karma", "keel", "keenly", "keto", "keying",
    "khaki", "kidded", "kidder", "kipper", "kisses", "kiting", "kitsch", "knives",
    "knob", "kopeck", "labia", "ladder", "laded", "lake", "lands", "large", "larger",
    "larva", "lash", "lashes", "lathe", "lava", "lawful", "lawn", "layout", "lays",
    "leaden", "leaky", "leaner", "leave", "leech", "legs", "legume", "leis", "lemme",
    "levity", "lewd", "lids", "liken", "likest", "limb", "limit", "limp", "limy",
    "lined", "link", "lintel", "lion", "lips", "listen", "lither", "litter", "liven",
    "livest", "locate", "lode", "logic", "logo", "loon", "loonie", "looser", "lorn",
    "lost", "lotion", "lots", "loving", "luck", "lurch", "macro", "madly", "magnet",
    "mallow", "manage", "mantra", "maraud", "margin", "maroon", "masc", "match", "mats",
    "mature", "maxed", "meanly", "meaty", "medal", "memo", "mesas", "mescal", "miaow",
    "micron", "middy", "mien", "mild", "milf", "mingle", "minnow", "minty", "minuet",
    "misled", "missal", "modem", "molten", "momma", "mooed", "mope", "moped", "moping",
    "morose", "mortar", "mosses", "motley", "mound", "movie", "mucus", "muff", "mufti",
    "mule", "multi", "mussel", "muted", "mutiny", "muumuu", "myrrh", "nacho", "nagged",
    "nanny", "napped", "natl", "naught", "nearby", "neath", "neatly", "needle", "needy",
    "nets", "netted", "netter", "nicest", "nicked", "ninety", "nipped", "nitwit",
    "none", "noodle", "noon", "nose", "noshes", "notice", "noway", "nozzle", "nude",
    "nuking", "numbly", "oaken", "obey", "ochre", "octal", "octopi", "odious", "odor",
    "office", "ogre", "oils", "olives", "onus", "onuses", "onward", "opals", "opaque",
    "opiate", "optima", "orator", "ordure", "ossify", "otter", "ought", "outfox",
    "outset", "overdo", "ovule", "owed", "owning", "ozone", "pacify", "pads", "pallor",
    "pantie", "pantry", "panty", "papa", "papacy", "parity", "parley", "parody",
    "parrot", "pasted", "pastel", "path", "patois", "patter", "peak", "peat", "peeing",
    "pelvis", "peony", "peptic", "peruse", "petal", "petrol", "petted", "phalli",
    "phlox", "phobia", "phoney", "phyla", "phylum", "piano", "piazze", "picket",
    "pieced", "pies", "piggy", "pigsty", "pilaff", "pilaw", "pillar", "pined", "pinion",
    "pint", "pinup", "piped", "pitied", "pities", "piton", "pixy", "pizazz", "placed",
    "placid", "planes", "plaza", "plea", "plead", "pleat", "pledge", "plexus", "plough",
    "plover", "plushy", "plying", "pock", "poetic", "poked", "pokey", "poky", "polar",
    "polity", "pond", "pony", "pool", "poop", "poorly", "popes", "poppy", "porch",
    "posing", "poss", "potent", "powder", "pray", "prep", "preset", "prevue", "pricey",
    "priest", "prig", "prior", "priory", "prized", "profit", "pron", "pros", "prosy",
    "prowl", "proxy", "pucker", "pucks", "puking", "pulpit", "pulse", "pulsed", "puma",
    "pumice", "pump", "pundit", "pure", "purely", "purged", "putsch", "putt", "pyre",
    "quasi", "query", "quip", "rabbit", "rack", "racket", "ragged", "rammed", "rank",
    "rapped", "rarefy", "rarest", "raring", "raved", "ravels", "reach", "rebel",
    "rectal", "redid", "redoes", "reds", "refit", "reflex", "regent", "region",
    "reined", "reject", "rejoin", "relish", "renew", "reopen", "report", "resign",
    "resp", "resume", "retain", "retook", "retort", "reused", "revel", "rhyme",
    "riding", "rids", "rifest", "rile", "rill", "rime", "riming", "rink", "rinsed",
    "ripest", "risk", "ritual", "roads", "robber", "robot", "robs", "robust", "roil",
    "roof", "room", "rooted", "roots", "rosin", "rouged", "rovers", "rubble", "rueful",
    "rues", "rumble", "rump", "sacred", "safely", "safer", "safety", "saint", "samba",
    "sampan", "sane", "saucer", "save", "scalp", "scan", "scheme", "schist", "schrod",
    "schwa", "scone", "scummy", "scurf", "seal", "seamy", "seedy", "sells", "sensor",
    "serous", "served", "servo", "settee", "seven", "sexed", "sexing", "sexpot", "sexy",
    "shalt", "shaped", "shat", "shes", "shill", "shirt", "shlock", "shone", "shot",
    "shout", "shrew", "shrine", "shrub", "shuck", "sickle", "silage", "silent",
    "silica", "silky", "silo", "simian", "simmer", "size", "sizer", "skid", "skies",
    "skinny", "skull", "skycap", "slain", "slam", "sleaze", "sleek", "slice", "slily",
    "slogan", "slop", "slosh", "slow", "slum", "slump", "slur", "slyest", "slyly",
    "smarmy", "smell", "smelly", "smelt", "smidge", "smooch", "snack", "snarky",
    "sneak", "sneeze", "snide", "snuck", "soar", "sober", "sobs", "sofa", "soling",
    "sombre", "sonar", "sopped", "sore", "sought", "soup", "source", "span", "spare",
    "spate", "spec", "spelt", "spied", "spiky", "spirea", "spit", "splat", "spoken",
    "spot", "spray", "spur", "squab", "squawk", "squirm", "stadia", "staled", "stanza",
    "staple", "status", "stench", "step", "sties", "stifle", "stink", "stir", "stoker",
    "stomp", "strap", "street", "strewn", "string", "stripe", "stript", "struck",
    "stucco", "stump", "stupid", "stye", "suet", "sumo", "surest", "surtax", "svelte",
    "swatch", "sweets", "swing", "swirly", "syrup", "sysop", "tabbed", "tabby", "taboo",
    "tactic", "tagged", "taken", "taker", "talk", "tall", "tamale", "tamest", "tango",
    "tank", "tans", "tapir", "taps", "tarps", "tattle", "tattoo", "taupe", "tawny",
    "taxes", "tbsp", "teabag", "teas", "teazel", "tech", "tenon", "termly", "testes",
    "thesis", "thief", "thing", "third", "thong", "thrift", "throne", "tick", "tided",
    "tidily", "tilt", "tissue", "token", "tomcat", "tongue", "tonic", "toss", "toting",
    "toucan", "touch", "track", "tramp", "trash", "tree", "trendy", "tried", "trifle",
    "trig", "trons", "trudge", "tubby", "tugs", "tuned", "tunny", "tuxedo", "twill",
    "twirl", "twit", "typed", "typhus", "ulna", "umiak", "undone", "unjust", "unload",
    "unmake", "unpack", "unsay", "unsold", "untie", "untied", "until", "unveil",
    "unwary", "unwind", "unzip", "upkeep", "upland", "upload", "urinal", "uteri",
    "uvula", "vague", "valid", "vast", "vatted", "veer", "vegan", "velour", "vendor",
    "veneer", "vernal", "verse", "vestry", "veto", "vets", "vetted", "vice", "vied",
    "view", "vine", "vireo", "vising", "volt", "votary", "vulgar", "vulva", "wacky",
    "wader", "wail", "waited", "waived", "waking", "walled", "walnut", "walrus",
    "warier", "warty", "waster", "wave", "waver", "wavier", "weal", "wedged", "weep",
    "weird", "wetly", "wetter", "whale", "wharf", "wheat", "wheezy", "whelp", "when",
    "whilst", "whirl", "whiten", "wiener", "wild", "wiling", "wimpy", "windup",
    "winner", "wiped", "wiping", "within", "witty", "wive", "woks", "women", "woodsy",
    "woos", "woozy", "wound", "woven", "wraith", "wrong", "wrung", "xxviii", "yacht",
    "yanked", "yarn", "yellow", "yest", "yeti", "yonder", "yore", "zephyr", "zing",
    "zorch", "zygote",
)
